### PR TITLE
Add acceptance tests with cucumber and aruba

### PR DESCRIPTION
**Pull request by dividedmind**
I built a test harness container by hacking on buncker and pushed it to the docker hub.

I stashed the required changes at https://github.com/conjurinc/buncker/tree/work/cauldron-acceptance -- hopefully we'll integrate them someday so that hacking won't be necessary.

Note substitution tests fail miserably, hopefully they'll make it easier to fix.

### CODE REVIEW

**Comment by inscitiv-ops-dev** [comment]
Can one of the admins verify this patch?

**Comment by kgilpin** [comment]
We need the test container to not be a one off

**Comment by dividedmind** [comment]
What do you mean?

**Comment by kgilpin** [comment]
The last I knew, the tests are using a one-off, built-by-hand container.
How do we modify it, how is it maintained?

**Comment by inscitiv-ops-dev** [comment]
Can one of the admins verify this patch?

**Comment by dividedmind** [comment]
It's built by buncker as modified on that branch. It can be directly used to rebuild, or we could merge the changes into vanilla buncker (though probably not verbatim).

**Comment by inscitiv-ops-dev** [comment]
Can one of the admins verify this patch?

**Pull request merged**
