### PR TITLE
Bash completion

### PR DESCRIPTION
**Pull request by ryanprior**
More friendlier CLI to summon

### CODE REVIEW

**Comment by inscitiv-ops-dev** [comment]
Can one of the admins verify this patch?

**Comment by dividedmind** [comment]
I'm getting a `_init_completion: command not found` error. Where is `_init_completion` from?

**Comment by ryanprior** [comment]
In Debian it's defined in `/usr/share/bash-completion/bash_completion` from package [bash-completion](https://packages.debian.org/sid/bash-completion)

On OSX I believe it's available via `brew` as [BashCompletion](http://brewformulas.org/BashCompletion) or you could install the Debian package via MacPorts.

**Comment by dividedmind** [comment]
Ah, I had to `. /etc/profile.d/bash-completion.sh` first (bash isn't my primary shell). Works great, thanks!

**Comment by dividedmind** [comment]
One thing: is it possible for it to complete providers from paths, not only from libexec? Ie. if I have an executable `./test-provider.sh`, then I want it to complete `summon -p ./` into `summon -p ./test-provider.sh`. If there's no path prefix then it should just complete from libexec, as it does now.

**Pull request merged**
